LabDrugManageSystem/Lab/urls.py
from django.urls import path

from . import views

app_name = 'Lab'

urlpatterns = [
    # 学生端
    path('', views.loginOfAll, name='loginOfAll'),  # 总登录页面
    path('index', views.index, name='index'),  # 学生首页
    path('ins_index', views.ins_index, name='ins_index'),  # 仪器首页
    path('lab', views.lab, name='lab'),  # 实验室信息
    path('browseHistory', views.borrowHistory, name='borrowHistory'),  # 药品借用历史记录
    path('ins_browseHistory', views.borrowInsHistory, name='borrowInsHistory'),  # 仪器借用历史记录
    path('userCentre', views.userCentre, name='userCentre'),  # 用户中心
    path('changePassword', views.changePassword, name='changePassword'),  # 修改密码
    path('about', views.about, name='about'),  # 关于
    path('subAndBo/<int:medicine_id>', views.subAndBo, name='subAndBo'),  # 借用药品
    path('ins_subAndBo/<int:ins_id>', views.ins_subAndBo, name='ins_subAndBo'),  # 借用仪器
    path('ins_addAndTu/<int:bor_id>', views.ins_addAndTu, name='ins_addAndTu'),  # 借用仪器
    path('login/', views.loging, name='login'),  # 登录
    path('logout/', views.logouting, name='logout'),  # 退出登录
    path('register/', views.register, name='register'),  # 注册
    path('detail/<int:medicineId>', views.medicineDetail, name='medicineDetail'),  # 药品详情
    path('medicineSearch/', views.medicineSearch, name='medicineSearch'),  # 药品搜索
    path('user_info/', views.userInfo, name='userInfo'),  # 用户信息
    path('download_file/<int:doc_id>', views.download_file, name='download_file'),  # 下载文件

    # 后台管理系统的三个分析图表
    path('admin/chart1/', views.chart1, name='chart1'),
    path('admin/chart2/', views.chart2, name='chart2'),
    path('admin/predict/', views.predict, name='predict'),
]

LabDrugManageSystem/LabDrugManageSystem/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import Lab.urls

urlpatterns = [
                  path('admin/', admin.site.urls),  # 后台管理
                  path('', include(Lab.urls)),  # 系统管理
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LabDrugManageSystem/Lab/models.py
from django.db import models
from django.contrib.auth.models import User


# 实验室信息表
class Lab(models.Model):
    name = models.CharField('实验室名称', max_length=20)
    description = models.TextField('实验室简介', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'lab'
        verbose_name = '实验室信息表'
        verbose_name_plural = verbose_name


# 药品信息表
class Medicine(models.Model):
    number = models.CharField('药品编号', max_length=13, unique=True)
    name = models.CharField('药品名', max_length=200)
    detail = models.TextField('药品信息', max_length=2000, blank=True)
    nowtotal = models.IntegerField('药品剩余量', default=0)
    usedtotal = models.IntegerField('药品用量', default=0)
    riskfactor = models.IntegerField('危险性（值越大越危险）', default=0)
    user_risk = models.IntegerField('使用风险度（值越大缺少时影响越大）', default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'medicine'
        verbose_name = '药品信息表'
        verbose_name_plural = verbose_name
        ordering = ('number',)


# 仪器信息表
class Instrument(models.Model):
    ins_no = models.CharField('仪器编号', max_length=13, unique=True)
    ins_name = models.CharField('仪器名称', max_length=200)
    ins_detail = models.TextField('仪器信息', max_length=2000, blank=True)
    ins_nowtotal = models.IntegerField('仪器剩余数', default=0)
    ins_bototal = models.IntegerField('仪器借用数', default=0)

    def __str__(self):
        return self.ins_name

    class Meta:
        db_table = 'instrument'
        verbose_name = '仪器信息表'
        verbose_name_plural = verbose_name
        ordering = ('ins_no',)


# 学生信息表
class CommonUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickyName = models.CharField('昵称', blank=True, max_length=50)
    cate = models.BooleanField('是否学生', default=False)
    faculty = models.CharField('系别', max_length=20, blank=True, default='undefine')

    class Meta:
        db_table = 'common_user'
        verbose_name = '学生信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.user)


# 借用药品记录表
class Borrow(models.Model):
    user = models.ForeignKey(CommonUser, on_delete=models.CASCADE, verbose_name='借用人')
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, verbose_name='实验室')
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE, verbose_name='借用药品', )
    medicineUsedNum = models.PositiveIntegerField('药品使用量(/g或/ml)', default=0)
    boDate = models.DateTimeField('借用时间', auto_now_add=True)

    class Meta:
        db_table = 'borrow'
        verbose_name = '借用药品记录表'
        verbose_name_plural = verbose_name


# 借用仪器纪录表
class InsBorrow(models.Model):
    ins_user = models.ForeignKey(CommonUser, on_delete=models.CASCADE, verbose_name='借用人')
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE, verbose_name='借用仪器', )
    ins_boNum = models.PositiveIntegerField('借用数量', default=0)
    ins_boDate = models.DateTimeField('借用时间', auto_now_add=True)
    ins_tuData = models.CharField('归还时间', max_length=100, default="暂未归还")

    class Meta:
        db_table = 'ins_borrow'
        verbose_name = '借用仪器记录'
        verbose_name_plural = verbose_name


# 文件信息表
class Doc(models.Model):
    file_name = models.CharField('文件名字', max_length=50)
    file_obj = models.FileField('文件', upload_to='files/')
    upload_time = models.DateTimeField('上传时间', auto_now_add=True)

    def __str__(self):
        return self.file_name

    class Meta:
        db_table = 'doc'
        verbose_name = '文件信息表'
        verbose_name_plural = verbose_name

LabDrugManageSystem/Lab/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


# 用户注册表单
class UserCustomRegister(UserCreationForm):
    nickyName = forms.CharField(required=False, max_length=50)
    cate = forms.BooleanField(required=True)
    faculty = forms.CharField(required=True, max_length=20)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',
                  'nickyName', 'cate', 'faculty')


# 用户修改信息表单
class UserCustomChange(UserChangeForm):
    nickyName = forms.CharField(required=False, max_length=50)

    class Meta:
        model = User
        fields = ('email', 'password', 'nickyName')

LabDrugManageSystem/Lab/views.py
import datetime
import json

import requests
from dateutil.relativedelta import relativedelta
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage, EmptyPage
from django.db import connection
from django.db.models import Q, Count
from django.http import HttpResponse, FileResponse
from django.shortcuts import render, redirect
from django.utils.encoding import escape_uri_path

from .forms import UserCustomRegister, UserCustomChange
from .models import *


# 总的登录界面
def loginOfAll(request):
    return render(request, 'loginOfAll.html')


# 首页，显示药品列表
def index(request):
    if request.method == 'GET':
        MedicineList = Medicine.objects.all()
        LabList = Lab.objects.all()
        # 将数据按照规定每页显示 8 条, 进行分割
        paginator = Paginator(MedicineList, 8)
        # 分页获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        medicineList = paginator.get_page(page)
        content = {
            'medicineList': medicineList,  # 药品信息
            'LabList': LabList,  # 实验室信息
            'currentUser': request.user,  # 用户信息
        }
        return render(request, 'index.html', content)


# 实验室列表信息
def lab(request):
    LabList = Lab.objects.all()
    # 分页显示，将数据按照规定每页显示 8 条, 进行分割
    paginator = Paginator(LabList, 8)
    # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
    page = request.GET.get('page')
    try:
        labList = paginator.page(page)
    except PageNotAnInteger:
        # 如果请求的页数不是整数, 返回第一页。
        labList = paginator.page(1)
    except EmptyPage:
        # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
        labList = paginator.page(paginator.num_pages)
    except InvalidPage:
        # 如果请求的页数不存在, 重定向页面
        return HttpResponse('找不到页面的内容！')
    content = {
        'labList': labList,  # 实验室信息
    }
    return render(request, 'lab.html', content)


# 关于界面，只接受get请求
def about(request):
    if request.method == 'GET':
        docList = Doc.objects.all()  # 文件信息
        return render(request, 'about.html', locals())


# 搜索药品信息
def medicineSearch(request):
    LabList = Lab.objects.all()  # 实验室信息
    if request.method == 'POST':
        searchType = request.POST['searchType']  # 按照什么搜索
        keyword = request.POST['keyword']  # 搜索内容
        # 按照名字搜索
        if searchType == 'name':
            MedicineList = Medicine.objects.filter(name__contains=keyword)
        # 按照编号搜索
        elif searchType == 'number':
            MedicineList = Medicine.objects.filter(number__contains=keyword)
        # 按照全部搜索
        else:
            MedicineList = Medicine.objects.filter(Q(name__contains=keyword) |
                                                   Q(number__contains=keyword))
        # 将数据按照规定每页显示 8 条, 进行分割
        paginator = Paginator(MedicineList, 8)
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        # 分页后的数据
        medicineList = paginator.get_page(page)
        content = {'medicineList': medicineList,
                   'LabList': LabList,
                   'currentUser': request.user
                   }
        return render(request, 'index.html', content)


# 登陆
def loging(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'login.html', {'error': '用户不存在或密码错误，请检查！'})
        else:
            login(request, user)
            return redirect('Lab:index')
    else:
        return render(request, 'login.html')


# 退出登录
def logouting(request):
    logout(request)
    return redirect('Lab:index')


# 注册
def register(request):
    if request.method == 'POST':
        registerForm = UserCustomRegister(request.POST)
        if registerForm.is_valid():
            registerForm.save()
            newUser = authenticate(username=registerForm.cleaned_data['username'],
                                   password=registerForm.cleaned_data['password1'])
            newUser.email = registerForm.cleaned_data['email']
            CommonUser(user=newUser, nickyName=registerForm.cleaned_data['nickyName'],
                       cate=registerForm.cleaned_data['cate'],
                       faculty=registerForm.cleaned_data['faculty']).save()
            login(request, newUser)
            return redirect('Lab:index')
    else:
        registerForm = UserCustomRegister()
    content = {'registerForm': registerForm}
    return render(request, 'register.html', content)


# 用户查看个人信息，需要先登录
@login_required(login_url='Lab:login')
def userCentre(request):
    # 修改个人信息
    if request.method == 'POST':
        changeForm = UserCustomChange(request.POST, instance=request.user)
        if changeForm.is_valid():
            changeForm.save()
            request.user.commonuser.nickyName = changeForm.cleaned_data['nickyName']
            request.user.commonuser.save()
    else:
        pass
    changeForm = UserCustomChange()
    content = {'currentUser': request.user, 'changeForm': changeForm}
    return render(request, 'userCentre.html', content)


# 用户修改密码
@login_required(login_url='Lab:login')
def changePassword(request):
    if request.method == 'POST':
        changepasswordForm = PasswordChangeForm(data=request.POST, user=request.user)
        if changepasswordForm.is_valid():
            changepasswordForm.save()
            return redirect('Lab:login')
    else:
        pass
    changepasswordForm = PasswordChangeForm(user=request.user)
    content = {
        'currentUser': request.user,
        'changepasswordForm': changepasswordForm
    }
    return render(request, 'changePassword.html', content)


# 学生借用药品历史查看
@login_required(login_url='Lab:login')
def borrowHistory(request):
    if request.method == 'GET':
        user = CommonUser.objects.filter(user=request.user).first()
        MedicineListTarget = Borrow.objects.filter(user=user).order_by("-boDate")
        MedicineList = []
        for borrowInfo in MedicineListTarget:
            borrowTime = datetime.datetime.now().day - borrowInfo.boDate.day  # 已经借用的天数
            MedicineList.append((Medicine.objects.get(pk=borrowInfo.medicine_id), borrowInfo, borrowTime))
        content = {
            'MedicineList': MedicineList,
            'currentUser': request.user
        }
        return render(request, 'borrowHistory.html', content)


# 药品详情
def medicineDetail(request, medicineId):
    if request.method == 'GET':
        thisMedicine = Medicine.objects.get(id=medicineId)
        content = {
            'medicine': thisMedicine,
        }
        return render(request, 'detail.html', content)


# 借用药品
@login_required(login_url='Lab:login')
def subAndBo(request, medicine_id):
    if request.method == 'POST':
        thisLab = request.POST.get('lab')  # 借用的实验室
        thisNum = int(request.POST.get('medicineUsedNum'))  # 药品编号
        thisUser = User.objects.get(pk=request.user.id)  # 取用用户
        # p判断实验室是否存在
        labTrue = Lab.objects.filter(name__exact=thisLab).count()
        thisMedicine = Medicine.objects.get(pk=medicine_id)
        # 取用的数量大于库存数量
        if thisMedicine.nowtotal <= thisNum:
            return render(request, 'error.html', {"failInfo": "借用失败！库存不足啦！"})
        # 不存在填写的实验室名称
        elif labTrue == 0:
            return render(request, 'error.html', {"failInfo": "您输入的实验室不存在！"})
        # 满足条件可以取用
        else:
            thisMedicine.usedtotal += thisNum
            thisMedicine.nowtotal -= thisNum
            thisMedicine.save()
            newBorrow = Borrow(user=thisUser.commonuser, lab=Lab.objects.get(name=thisLab),
                               medicine=thisMedicine, medicineUsedNum=thisNum)
            newBorrow.save()
            return redirect('Lab:index')


# 用户信息界面
def userInfo(request):
    return render(request, 'usr_info.html')


# 仪器列表
def ins_index(request):
    if request.method == 'GET':
        InstrumentList = Instrument.objects.all()
        # 将数据按照规定每页显示 8 条, 进行分割
        paginator = Paginator(InstrumentList, 8)
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        instrumentList = paginator.get_page(page)
        content = {
            'instrumentList': instrumentList,
            'currentUser': request.user,
        }
        return render(request, 'ins_index.html', content)


# 仪器借用
@login_required(login_url='Lab:login')
def ins_subAndBo(request, ins_id):
    if request.method == 'POST':
        thisNum = int(request.POST.get('insUsedNum'))  # 仪器数量
        thisUser = User.objects.get(pk=request.user.id)  # 借用的用户
        thisInstrument = Instrument.objects.get(pk=ins_id)  # 仪器信息
        # 借用数量超过了库存数量
        if thisInstrument.ins_nowtotal <= thisNum:
            return render(request, 'error.html', {"failInfo": "借用失败！库存不足！"})
        # 满足借用条件
        else:
            thisInstrument.ins_bototal += thisNum  # 借出数量增加
            thisInstrument.ins_nowtotal -= thisNum  # 剩余量减少
            thisInstrument.save()
            newBorrow = InsBorrow(ins_user=thisUser.commonuser,
                                  instrument=thisInstrument, ins_boNum=thisNum)
            newBorrow.save()
            return redirect('Lab:ins_index')


# 仪器归还
@login_required(login_url='Lab:login')
def ins_addAndTu(request, bor_id):
    if request.method == 'POST':
        thisNum = int(request.POST.get('insTurnedNum'))  # 仪器归还数量
        thisUser = User.objects.get(pk=request.user.id)  # 借用的用户
        thisInsbro = InsBorrow.objects.get(pk=bor_id)  # 借用信息
        print(thisInsbro.instrument_id)
        thisInstrument = Instrument.objects.get(pk=thisInsbro.instrument_id)  # 仪器信息
        print(thisNum, thisInsbro.ins_boNum)

        # 归还数量大于借用的数量
        if thisInsbro.ins_boNum < thisNum:
            return render(request, 'error.html', {"failInfo": "归还失败！归还数量有误！"})

        # 归还部分数量

LabDrugManageSystem/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keyword" content="{% block keyword %}BASE_HTML{% endblock %}">
    <meta name="description" content="{% block description %}BASE_HTML{% endblock %}">
    <meta name="author" content="skywalker">
    <link rel="icon" href="{% static 'icons/lab.png' %}">
    <title>实验室药品分析与管理系统
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% block css %}
    {% endblock css %}">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <img src="{% static 'icons/lab.png' %}"
         width="33" height="33" class="d-inline-block align-top" alt="">&nbsp;&nbsp;
    <a class="navbar-brand" href="#">实验室药品管理系统</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item  {% block indexHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'Lab:index' %}">药品列表 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item  {% block insindexHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'Lab:ins_index' %}">仪器列表 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item  {% block labHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'Lab:lab' %}">实验室列表<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% block userHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'Lab:userInfo' %}">个人中心</a>
            </li>
            <li class="nav-item {% block aboutHighlight %}{% endblock %}">
                <a class="nav-link disabled" href="{% url 'Lab:about' %}">关于</a>
            </li>
        </ul>

        <form style="margin-right: 50px" class="form-inline my-2 my-lg-0" action="{% url 'Lab:medicineSearch' %}"
              method="POST">
            {% csrf_token %}
            <input name='keyword' class="form-control mr-sm-2" type="text" placeholder="请输入要查询的药品" aria-label="Search">
            <div class="form-row align-items-center">
                <div class="col-auto my-1">
                    <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Preference</label>
                    <select name='searchType' class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                        <option selected>所有</option>
                        <option value="name">药品名</option>
                        <option value="number">药品编号</option>
                    </select>
                </div>
            </div>&nbsp;&nbsp;&nbsp;&nbsp;
            <button style="width: 100px" class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>

        {% if user.is_authenticated %}
            <a href="{% url 'Lab:logout' %}">
                <button style="width: 150px" class="btn btn-primary">{{ user.username }}, 登出</button>
            </a>
            </div>
        {% else %}
            <a href="{% url 'Lab:login' %}">
                <button style="width: 100px" class="btn btn-primary">登录</button>
            </a>
            </div>
        {% endif %}
</nav>

<main role="main" class="container">
    {% block main_block %}
    {% endblock %}

</main>
<footer class="footer">
    <div class="copyright" style="text-align: center">
        <p>
            <span>Copyright (C). create by BHML 2023, All Rights Reserved</span>&nbsp;&nbsp;
            <a href="/admin">管理员入口</a>
        </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript  -->
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

LabDrugManageSystem/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
 - 用户登录
{% endblock %}

{% block css %}
    {% static 'css/login.css' %}
{% endblock %}

{% block main_block %}
    {% if error %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <div class="text-center welcomeSlogan"><strong>{{ error }}</strong></div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="row">
        <form class="form-signin" action="" method="POST">
            {% csrf_token %}
            <div class="text-center mb-4">
                <img class="mb-4" src="{% static 'icons/lab.png' %}" alt="" width="106" height="106">
                <h1 class="h3 mb-3 font-weight-normal">实验室药品分析管理系统</h1>
                <p> 欢迎登录,未注册请先 <a href="{% url 'Lab:register' %}">立即注册</a></p>

            </div>

            <div class="form-label-group">
                <input name="username" id="inputUserName" class="form-control" placeholder="请输入学号" required=""
                       autofocus="" type="text">
                <label for="inputUserName">学号</label>
            </div>

            <div class="form-label-group">
                <input name="password" id="inputPassword" class="form-control" placeholder="请输入密码" required=""
                       type="password">
                <label for="inputPassword">密码</label>
            </div>

            {#      <div class="checkbox mb-3">#}
            {#        <label>#}
            {#          <input value="remember-me" type="checkbox"> Remember me#}
            {#        </label>#}
            {#      </div>#}
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>
    </div>
{% endblock %}

LabDrugManageSystem/templates/userCentre.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
    -用户中心
{% endblock %}

{% block css %}
    {% static 'css/userCentre.css' %}
{% endblock %}
{% block main_block %}
    {% if changeForm.errors %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">修改信息中出现问了哦！</h4>
            <p>{{ changeForm.errors }}</p>
            <hr>
            <p class="mb-0">如要修改请注意以上的错误：</p>
        </div>
    {% endif %}
    <div>
        <form class="form-group" action="" method="POST" style="width: 40%;margin-left: 30%;margin-top: 3%">
            <h2>修改个人信息</h2>
            <hr>
            {% csrf_token %}
            <div class="form-group row">
                <label for="id_username" class="col-sm-3 col-form-label">用户名:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="staticUsername"
                           value="{{ currentUser.username }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="id_nickyName" class="col-sm-3 col-form-label">昵称:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="nickyName" maxlength="50" id="id_nickyName"
                           placeholder="{{ currentUser.commonuser.nickyName }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="id_cate" class="col-sm-3 col-form-label">用户类型:</label>
                <div class="col-sm-9">
                    {% if currentUser.commonuser %}
                        <input type="text" readonly class="form-control-plaintext" id="staticCate"
                               value="学生">
                    {% else %}
                        <input type="text" readonly class="form-control-plaintext" id="staticCate"
                               value="教师">
                    {% endif %}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_faculty" class="col-sm-3 col-form-label">院系:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="staticFaculty"
                           value="{{ currentUser.commonuser.faculty }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="id_email" class="col-sm-3 col-form-label">邮箱:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="email" name="email" maxlength="254" id="id_email"
                           placeholder="{{ currentUser.email }}">
                </div>
            </div>
            <button class="btn btn-primary" type="submit" style="width: 100%">保存</button>
        </form>
    </div>

{% endblock %}

LabDrugManageSystem/templates/usr_info.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %} - 用户信息
{% endblock %}

{% block css %}
    {% static 'css/usr_info.css' %}
{% endblock %}

{% block main_block %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <section id="content" class="clearfix">
        <section class="light-buttons">
            <div class="right">
                <h1 class="dark-header">个人信息</h1>
                <a href="{% url 'Lab:userCentre' %}" class="button lightbg-blue clearfix"><span>个人信息</span>
                    <div class="icon">
                        <div class="arrow"></div>
                    </div>
                </a><a href="{% url 'Lab:borrowHistory' %}" class="button lightbg-pink clearfix"><span>借阅药品历史</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a> <a href="{% url 'Lab:borrowInsHistory' %}" class="button lightbg-green clearfix"><span>借阅仪器历史</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a><a href="{% url 'Lab:changePassword' %}" class="button lightbg-orange clearfix"><span>修改密码</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a>
            </div>
        </section>
    </section>
{% endblock %}